apiVersion: v2
name: knative-serving
description: A knative serving Helm chart for Kubernetes
type: application
version: 3.0.0
appVersion: v0.16.0
icon: https://avatars2.githubusercontent.com/u/35583233?s=200&v=4
